name: .NET Class Library Build

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master    

jobs:
  build-project:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Class Library
        run: dotnet build --configuration Release --no-restore

      - name: Run Unit Tests
        run: dotnet test --configuration Release --no-build --verbosity normal --settings ./Runsettings/chrome.runsettings

